### ISSUE TITLE
github service crashing

### ISSUE THREAD

**Issue by Georgette** [nodezoo/nodezoo-web#44] opened 2016-03-28 23:28 UTC
Consecutive info queries are causing github service to fail ( I might need to move this issue to another repo)

I tried using only seneca and lodash, and able to get the service to crash by toggling between them in the route

```
/info/{module_name}

```

here is a crash report when querying for argosy

route:

```
/info/argosy

```

(so searching for argosy)

log:

```
Seneca Fatal Error
==================

Message: seneca: No matching action pattern found for { data:    { name: 'argosy',     user: 'jasonpincin',     repo: 'argosy',     stars: 3,     watches: 1,     forks: 2,     last: '2016-02-04T16:47:08Z',     url: 'http://github.com/jasonpincin/argosy',     'id$': 'argosy' },  role: 'search',  cmd: 'insert' }, and no default result provided (using a default$ property).

Code: act_not_found

Details: { args: '{ data:    { name: \'argosy\',     user: \'jasonpincin\',     repo: \'argosy\',     stars: 3,     watches: 1,     forks: 2,     last: \'2016-02-04T16:47:08Z\',     url: \'http://github.com/jasonpincin/argosy\',     \'id$\': \'argosy\' },  role: \'search\',  cmd: \'insert\' }' }

Stack:
    at Object.errormaker [as error] (/Users/gege/nearform/nodezoo-system/node_modules/nodezoo-github/node_modules/eraro/eraro.js:94:15)
    at Object.execute_action [as fn] (/Users/gege/nearform/nodezoo-system/node_modules/nodezoo-github/node_modules/seneca/seneca.js:1054:29)
    at Immediate._onImmediate (/Users/gege/nearform/nodezoo-system/node_modules/nodezoo-github/node_modules/seneca/node_modules/gate-executor/gate-executor.js:135:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

Instance: Seneca/1.2.0/xdveia4tagum/1459205683772/28075/undefined
  ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance, see senecajs.org/fatal.html)
    at Object.execute_action [as fn] (/Users/gege/nearform/nodezoo-system/node_modules/nodezoo-github/node_modules/seneca/seneca.js:1059:27)

When: 2016-03-28T22:55:18.944Z

Log: [sys,seneca,1.2.0,xdveia4tagum/1459205683772/28075/undefined,act_not_found,seneca: No matching action pattern f

Node:
  { http_parser: '2.5.2', node: '4.4.1', v8: '4.5.103.35', uv: '1.8.0', zlib: '1.2.8', ares: '1.10.1-DEV', icu: '56.1', modules: '46', openssl: '1.0.2g' },
  { debug: false, uv: true, ipv6: true, tls_npn: true, tls_sni: true, tls_ocsp: true, tls: true },
  [ 'Binding contextify', 'Binding natives', 'NativeModule events', 'NativeModule buffer', 'Binding buffer', 'NativeModule internal/util', 'Binding util', 'NativeModule timers', 'Binding timer_wrap', 'NativeModule _linklist', 'NativeModule assert', 'NativeModule util', 'Binding uv', 'NativeModule path', 'NativeModule module', 'NativeModule internal/module', 'NativeModule vm', 'NativeModule fs', 'Binding fs', 'NativeModule constants', 'Binding constants', 'NativeModule stream', 'NativeModule _stream_readable', 'NativeModule _stream_writable', 'NativeModule _stream_duplex', 'NativeModule _stream_transform', 'NativeModule _stream_passthrough', 'Binding fs_event_wrap', 'NativeModule os', 'Binding os', 'NativeModule crypto', 'Binding crypto', 'NativeModule internal/streams/lazy_transform', 'NativeModule string_decoder', 'NativeModule net', 'NativeModule internal/net', 'Binding cares_wrap', 'Binding tty_wrap', 'Binding tcp_wrap', 'Binding pipe_wrap', 'Binding stream_wrap', 'NativeModule dns', 'NativeModule url', 'NativeModule punycode', 'NativeModule querystring', 'NativeModule http', 'NativeModule _http_incoming', 'NativeModule _http_common', 'NativeModule internal/freelist', 'Binding http_parser', 'NativeModule _http_outgoing', 'NativeModule _http_server', 'NativeModule _http_agent', 'NativeModule _http_client', 'NativeModule https', 'NativeModule tls', 'NativeModule _tls_common', 'NativeModule _tls_wrap', 'NativeModule _stream_wrap', 'Binding js_stream', 'Binding tls_wrap', 'NativeModule _tls_legacy', 'NativeModule zlib', 'Binding zlib', 'NativeModule dgram', 'Binding udp_wrap', 'NativeModule console', 'Binding signal_wrap', 'NativeModule repl', 'NativeModule readline', 'NativeModule domain', 'NativeModule tty', 'NativeModule cluster', 'NativeModule child_process', 'Binding spawn_sync', 'NativeModule internal/child_process', 'Binding process_wrap', 'NativeModule internal/socket_list', 'NativeModule internal/cluster' ]

Process:
  pid=28075, arch=x64, platform=darwin,
  path=/Users/gege/.nvm/versions/node/v4.4.1/bin/node,
  argv=[ '/Users/gege/.nvm/versions/node/v4.4.1/bin/node',  '/Users/gege/nearform/nodezoo-system/node_modules/nodezoo-github/srv/github-dev.js',  '--seneca.options.tag=nodezoo-github',  '--seneca-log=type:act' ],
  env={ elasticsearch_PORT_9300: '9200',  MANPATH: '/Users/gege/.nvm/versions/node/v4.4.1/share/man:/usr/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man',  metrics_PORT: '10001',  mesh_PORT: '10000',  TERM_PROGRAM: 'iTerm.app',  NVM_CD_FLAGS: '',  TERM: 'xterm-256color',  SHELL: '/bin/bash',  TMPDIR: '/var/folders/cl/vzm9v8gx7w57_h2xghl20j740000gn/T/',  elasticsearch_PORT_9200: '9200',  Apple_PubSub_Socket_Render: '/private/tmp/com.apple.launchd.0eR56y4VZi/Render',  NVM_PATH: '/Users/gege/.nvm/versions/node/v4.4.1/lib/node',  DOCKER_HOST: 'tcp://172.16.183.129:2376',  influx_PORT_8083: '8086',  search_PORT: '10003',  npm_PORT: '10004',  influx_PORT_8086: '8086',  USER: 'gege',  NVM_DIR: '/Users/gege/.nvm',  SERVICE_HOST: '0.0.0.0',  DOCKER_MACHINE_NAME: 'default',  SERVICE_PORT: '20005',  concorda_PORT: '10008',  SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.0WBSeFgNkY/Listeners',  TOKEN: 'f2c56d03f8652f282658cfb5c8cb0409f0fa2fb3',  __CF_USER_TEXT_ENCODING: '0x1F5:0x0:0x0',  github_PORT: '10005',  DOCKER_TLS_VERIFY: '1',  web_PORT: '10007',  PROXY_HOST: '127.0.0.1',  PATH: '/Users/gege/.nvm/versions/node/v4.4.1/bin:/Users/gege/.nvm/versions/node/v4.4.1/lib/node_modules/fuge/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin',  NVM_NODEJS_ORG_MIRROR: 'https://nodejs.org/dist',  PWD: '/Users/gege/nearform/nodezoo-system/node_modules/nodezoo-github',  travis_PORT: '10006',  LANG: 'en_US.UTF-8',  ITERM_PROFILE: 'Default',  XPC_FLAGS: '0x0',  XPC_SERVICE_NAME: '0',  HOME: '/Users/gege',  COLORFGBG: '7;0',  SHLVL: '1',  DOCKER_CERT_PATH: '/Users/gege/.docker/machine/machines/default',  info_PORT: '10002',  vidi_PORT: '10009',  ITERM_SESSION_ID: 'w0t0p1:C073D28C-AD08-47A5-899F-D2FEE6FE9EDE',  LOGNAME: 'gege',  NVM_BIN: '/Users/gege/.nvm/versions/node/v4.4.1/bin',  NVM_IOJS_ORG_MIRROR: 'https://iojs.org/dist' }

SENECA TERMINATED (on timeout) at 2016-03-28T22:55:30.059Z.

```

**Comment by mcdonnelldean** [comment] 2016-03-29 07:59
@Georgette This is due to a change in search, I'm resolving now, will close this when it is fixed. The issue is github is trying to talk to search but it doesn't know anything about it.

**Comment by mcdonnelldean** [comment] 2016-04-04 08:43
This should now be fixed.

**Closed by mcdonnelldean** 2016-04-04 08:43 UTC
Labels: bug
